@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title SnapMatch - Container Diagram

Person(candidate, "Соискатель")
Person(hr, "HR-специалист")

System_Boundary(SnapMatch, "SnapMatch") {
    Container(snapmatch, "SnapMatch", "Ktor + LLM API: принимает резюме, валидирует PDF, сохраняет в MinIO, анализирует резюме на соответствие вакансии c помощью LLM")
    ContainerDb(db, "PostgreSQL", "Хранит данные вакансий, кандидатов и истории откликов")
    Container(storage, "MinIO", "S3-хранилище", "Хранит оригинальные PDF-файлы")
}

candidate --> snapmatch : Загружает резюме
snapmatch --> storage : Сохраняет PDF
snapmatch --> db : Записывает результат анализа и получает данные из БД
hr --> snapmatch : Просматривает результаты
snapmatch --> candidate : Уведомляет о результате анализа резюме

@enduml